#!/bin/bash

Reset='\e[0m'       # Text Reset
# Regular Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

link () {

  if [ -L $2 ]
  then
    info "removing old $2"
    rm $2
  fi

  if [ -w $2 ] || [ -d $2 ];
  then
    info "moving $2 to $2_bak"
    mv $2{,_bak}
  fi

  printf "  [%bLink%b] $1 -> $2\n" $Cyan $Reset
  ln -s $1 $2
}

heading () {
  printf "$Purple ===============$Reset $1 $Purple===============$Reset\n"
}

info () {
  printf "  [$Blue .. $Reset] $1\n"
}

question () {
  printf "\r  [$Yellow ?? $Reset]$1 "
}

success () {
  printf "\r\033[2K  [$Green OK $Reset] $1\n"
}
