#!/bin/bash
source helpers

for setup in $(ls */setup*);
do
  if [ -x $setup ]
  then
    question "Install module - ${setup}? (Y)"
    read -e install
    if [ 'Y' == "$install" ] || [ 'y' == "$install" ] || [ '' == "$install" ]
    then
      sh ./$setup
    fi
  fi
done
