#!/bin/bash
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

source $SCRIPTPATH/../helpers

heading "Setting up git"

question ' Default git author name:'
read -e git_authorname
question ' Default git author email:'
read -e git_authoremail

sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" $SCRIPTPATH/gitconfig.template > $SCRIPTPATH/gitconfig
link $HOME/.gitconfig $SCRIPTPATH/gitconfig

success "git"
