#!/bin/bash
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

source $SCRIPTPATH/../helpers

heading "Setting up vim"

link ~/.vimrc $SCRIPTPATH/vimrc
link ~.vim $SCRIPTPATH/vim

info "Setting Up NeoBundle"
curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh

success "Vim setup"
