call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'amedw/vim-solarized-patched'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'maralla/completor.vim'

Plug 'scrooloose/nerdcommenter'

Plug 'janko-m/vim-test'
Plug 'skywind3000/asyncrun.vim'

Plug 'tpope/vim-fugitive'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'w0rp/ale'

call plug#end()

source $HOME/.vim/general.vim
source $HOME/.vim/keys.vim
source $HOME/.vim/plugins.vim


