call plug#begin('~/.vim/plugged')
" Themes & Styles
Plug 'aaron-edwards/vim-solarized-patched'
Plug 'sonph/onehalf' "For Fallback

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Navigation
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim'

" Autocomplete & Sytax
Plug 'Valloric/YouCompleteMe', { 'do': './install.py --omnisharp-completer --tern-completer' }
Plug 'w0rp/ale'

" Helpers
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'sjl/gundo.vim'

" Language
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'


call plug#end()

source $HOME/.vim/config/general.vim
source $HOME/.vim/config/keys.vim
source $HOME/.vim/config/plugins.vim

