#!/bin/bash
CURRENT_DIR=`pwd`
cd `dirname $0`
SCRIPT_PATH=`pwd -P`

source $SCRIPT_PATH/../helpers

heading "Setting up zsh with prezto"

if [ ! -d "${ZDOTDIR:-$HOME}/.zprezto" ]; then
  info "Cloning prezto repository"
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi

cd $CURRENT_DIR
