#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

bindkey '^R' history-incremental-search-backward

export JAVA_HOME="/usr/java/latest"
export GRADLE_HOME="/usr/gradle/gradle-2.5"
export PATH="$PATH:$JAVA_HOME/bin:$GRADLE_HOME/bin:/Users/aaron/.npm-packages/bin/firebase"

source "$HOME/.zshrc-custom"
source "$HOME/.bashrc"

export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"


# added by travis gem
[ -f /Users/aaron/.travis/travis.sh ] && source /Users/aaron/.travis/travis.sh
