#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

bindkey '^R' history-incremental-search-backward

bindkey -e

export JAVA_HOME="/usr/java/latest"
export GRADLE_HOME="/usr/gradle/gradle-2.5"
export PATH="$PATH:$JAVA_HOME/bin:$GRADLE_HOME/bin:/Users/aaron/.npm-packages/bin/firebase"

source "$HOME/.zshrc-custom"
source "$HOME/.bashrc"

export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"


# added by travis gem
[ -f /Users/aaron/.travis/travis.sh ] && source /Users/aaron/.travis/travis.sh

#export NVM_DIR=~/.nvm
#source $(brew --prefix nvm)/nvm.sh


## place this after nvm initialization!
#autoload -U add-zsh-hook
#load-nvmrc() {
  #local node_version="$(nvm version)"
  #local nvmrc_path="$(nvm_find_nvmrc)"

  #if [ -n "$nvmrc_path" ]; then
    #local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    #if [ "$nvmrc_node_version" = "N/A" ]; then
      #nvm install
    #elif [ "$nvmrc_node_version" != "$node_version" ]; then
      #nvm use
    #fi
  #elif [ "$node_version" != "$(nvm version default)" ]; then
    #echo "Reverting to nvm default version"
    #nvm use default
  #fi
#}
#add-zsh-hook chpwd load-nvmrc
#load-nvmrc


alias ppjson='python -m json.tool'
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/aaron/development/vicinity/portal-entry-point/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/aaron/development/vicinity/portal-entry-point/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/aaron/development/vicinity/portal-entry-point/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/aaron/development/vicinity/portal-entry-point/node_modules/tabtab/.completions/sls.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
